### ISSUE TITLE
[CHORE] 프로젝트 세팅

### ISSUE THREAD

**Issue by joshuayeyo** [joshuayeyo/claw#1]
# Description
프로젝트 시작을 위한 초기 세팅입니다.

# Todo
- [x] Vite로 프로젝트 시작
- [x] 필요한 라이브러리 설치
  - [x] emotion/styled
  - [x] @types/node
  - [x] Prettier
  - [x] ESLint
  - [x] framer-motion
  - [x] react-speech-recognition
  - [x] matter-js
  - [x] MUI  [사이트 링크](https://mui.com/material-ui/getting-started/installation/)
- [x] 절대경로 설정
- [x] prettier, eslint 설정

**Comment by joshuayeyo** [comment]
초기 설정 完了
