### ISSUE TITLE
[Feature] 게임 플레이를 위한 음성인식 추가

### ISSUE THREAD

**Issue by joshuayeyo** [joshuayeyo/claw#10]
## Description
게임 플레이를 위한 음성인식을 추가합니다.

## Todo
- [x] 음성인식을 위한 npm 라이브러리 설치
- [x] 음성인식을 위한 세팅
- [x] 음성인식 커스텀 훅 추가
- [x] 게임 Board와 연결
- [x] 게임 시작 화면 추가
