### ISSUE TITLE
[Feature] "뽑기" 동작 구현

### ISSUE THREAD

**Issue by joshuayeyo** [joshuayeyo/claw#12]
## Description
"뽑기" 명령어가 인식 되었을 경우, 해당 좌표에 해당하는 상품을 뽑습니다.
만약 좌표에 상품이 없다면 꽝입니다.

## Todo
- [ ] Result 모달 만들기
- [ ] Board와 연동
- [ ] Claw 움직임 횟수 제한 (5회)
  - [ ] 로직 구현
  - [ ] 남은 횟수 보여주는 UI Board에 추가
