### ISSUE TITLE
[Feature] 사이트 기본 레이아웃 설정

### ISSUE THREAD

**Issue by joshuayeyo** [joshuayeyo/claw#2]
# Description
사이트의 기본 레이아웃이 될, global CSS, Header, Body, Footer를 생성합니다.

# Todo
- [x] Global CSS 수정
  - [x] 반응형(태블릿, 컴퓨터)을 위한 media 구문 추가
  - [x] 사이트의 배경 색상 추가
  - [x] 폰트 `Pretendard` 추가
- [x] Header 추가
- [x] Board 레이아웃 추가
- [ ] Footer 추가

**Comment by joshuayeyo** [comment]
Footer 일단 보류
